---
- name: domain | install ad
  win_domain:
    dns_domain_name: "{{ domain }}"
    domain_netbios_name: "{{ netbios_domain }}"
    safe_mode_password: "{{ domain_safemode_password }}"
  register: ad

- name: domain | reboot server
  win_reboot:
    msg: "Installing AD. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 420
  when: ad.changed

- name: domain | ensure server is a domain controller
  win_domain_controller:
    dns_domain_name: "{{ domain }}"
    domain_admin_user: "{{ domain_admin }}"
    domain_admin_password: "{{ domain_admin_password }}"
    safe_mode_password: "{{ domain_safemode_password }}"
    state: domain_controller
    log_path: C:\ansible_win_domain_controller.txt

- name: domain | alter DC hosts to add DC name
  win_hosts:
    state: present
    canonical_name: "{{ domain_controller_fqdn}}"
    ip_address: "{{ domain_controller_ip }}"
