- name: client | install OpenSSH client
  win_shell: |
    Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
    Start-Service ssh-agent
    Set-Service -Name ssh-agent -StartupType 'Automatic'

- name: client | install OpenSSH server
  win_command: |
    powershell.exe -Command (Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0)
    Start-Service sshd
    Set-Service -Name sshd -StartupType 'Automatic'
  become: yes
  become_method: runas
  become_user: Administrator
