- name: packages | downloading Palantir's WEF script
  win_get_url:
    url: https://github.com/palantir/windows-event-forwarding/archive/master.zip
    dest: C:\Users\{{ ansible_user }}\AppData\Local\Temp\wef-Master.zip
    follow_redirects: all
    force: no

- name: packages | expanding WEF script
  win_shell: Expand-Archive -path 'C:\Users\{{ ansible_user }}\AppData\Local\Temp\wef-Master.zip' -destinationpath 'C:\Users\{{ ansible_user }}\AppData\Local\Temp' -Force

- name: packages | installing WEF script and starting service
  win_shell: |
    If ((Get-ScheduledTask -TaskName "AutorunsToWinEventLog" -ea silent) -eq $null)
    {
        . c:\Users\{{ ansible_user }}\AppData\Local\Temp\windows-event-forwarding-master\AutorunsToWinEventLog\Install.ps1
        Start-ScheduledTask -TaskName "AutorunsToWinEventLog"
        $Tsk = Get-ScheduledTask -TaskName "AutorunsToWinEventLog"
        if ($Tsk.State -ne "Running")
        {
            throw "AutorunsToWinEventLog scheduled tasks wasn't running after starting it"
        }
    }
