---
- name: change DNS server
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses: "{{ domain_controller_ip }}"
  when: not ansible_windows_domain_member

- name: domain | client block
  block:

  - name: domain | ensuring domain membership for clients
    win_domain_membership:
      dns_domain_name: "{{ domain }}"
      hostname: "{{ ansible_hostname }}"
      domain_admin_user: "{{ domain_admin }}"
      domain_admin_password: "{{ domain_admin_password }}"
      domain_ou_path: "OU=Workstations,{{ domain_component }}"
      state: domain
    register: domain_state_client

  - name: domain | rebooting client after joining domain
    win_reboot:
      msg: "Client is domain joined. Rebooting..."
      pre_reboot_delay: 15
      reboot_timeout: 240
      post_reboot_delay: 60
    when:
      - domain_state_client.changed
      - domain_state_client.reboot_required

  - name: domain | setting AutoAdminLogon autologin information
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
      name: AutoAdminLogon
      data: 1
  
  - name: domain | setting DefaultUserName autologin information
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
      name: DefaultUserName
      data: ".\\{{ local_admin }}"
  
  - name: domain | setting DefaultPassword autologin information
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
      name: DefaultPassword
      data: "{{ local_admin_password }}"

  when:
    - inventory_hostname in groups['clients']

- name: domain | WEF block
  block:

  - name: domain | ensuring domain membership for servers
    win_domain_membership:
      dns_domain_name: "{{ domain }}"
      hostname: "{{ ansible_hostname }}"
      domain_admin_user: "{{ domain_admin }}"
      domain_admin_password: "{{ domain_admin_password }}"
      domain_ou_path: "OU=Servers,{{ domain_component }}"
      state: domain
    register: domain_state_server
  
  - name: domain | rebooting server after joining domain
    win_reboot:
      msg: "Server is domain joined. Rebooting..."
      pre_reboot_delay: 15
      reboot_timeout: 360
      post_reboot_delay: 120
    when:
      - domain_state_server.changed
      - domain_state_server.reboot_required
  
  when:
    - inventory_hostname in groups['member_servers']
