---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Power off {{ domain }}
    vmware_guest_powerstate:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      folder: "/{{ datacenter_name }}/Lab"
      name: "{{ item }}"
      state: shutdown-guest
      state_change_timeout: 30
      validate_certs: false
    loop:
      - "{{ client_2_name }}"
      - "{{ client_1_name }}"
      - "{{ flsvr_name }}"
      - "{{ wef_name }}"
      - "{{ domain_controller_name }}"
      - "jumphost"
#      - "fortigate"
      - "rto"
    register: result
    failed_when:
      - result.changed
      - result.instance.hw_power_status != "poweredOff"
